"""Added name to farmer model

Revision ID: 0315382816b3
Revises: b198eed945c2
Create Date: 2025-07-08 09:39:38.710143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0315382816b3'
down_revision = 'b198eed945c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.drop_column('farm_size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_size', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###
