"""Updated feedback

Revision ID: 0a7e6daf9d9b
Revises: f8513bb3b5b6
Create Date: 2025-08-01 10:28:31.331111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a7e6daf9d9b'
down_revision = 'f8513bb3b5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('feedbacks_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('farmer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farmer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('feedbacks_ibfk_1'), 'farmers', ['farmer_id'], ['farmer_id'])

    # ### end Alembic commands ###
