"""Updated Booking model with farmer, user, and service relations

Revision ID: 352204a2cf6c
Revises: feb1effc5f5c
Create Date: 2025-07-30 12:40:28.314842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352204a2cf6c'
down_revision = 'feb1effc5f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
