"""Add homepage content models

Revision ID: 8d28b2e8e26a
Revises: 9e0493e00dc2
Create Date: 2025-08-07 14:40:45.294305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d28b2e8e26a'
down_revision = '9e0493e00dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_intro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_text', sa.String(length=255), nullable=False),
    sa.Column('intro_title', sa.String(length=255), nullable=False),
    sa.Column('intro_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_sections')
    op.drop_table('homepage_media')
    op.drop_table('home_intro')
    # ### end Alembic commands ###
