"""updated contact

Revision ID: 9e0493e00dc2
Revises: a1b2e711c128
Create Date: 2025-08-06 18:57:17.353847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0493e00dc2'
down_revision = 'a1b2e711c128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('reply')

    # ### end Alembic commands ###
