"""updated services

Revision ID: a1b2e711c128
Revises: 4a3880b36ffd
Create Date: 2025-08-06 17:17:38.627554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1b2e711c128'
down_revision = '4a3880b36ffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
